
build: Makefile midi-text-dump.c; cc -Wall -g -o midi-text-dump midi-text-dump.c
	
test1: ; ./midi-text-dump midi-testfile-1.mid

test2: ; ./midi-text-dump midi-testfile-2.mid

test3: ; ./midi-text-dump midi-testfile-3.mid

test4: ; ./midi-text-dump midi-testfile-4.mid
    
