
build: Makefile midi-text-dump2.c; cc -Wall -g -o midi-text-dump2 midi-text-dump2.c
	
run1: ; ./midi-text-dump2 midi-testfile-1.mid

run2: ; ./midi-text-dump2 midi-testfile-2.mid

run3: ; ./midi-text-dump2 midi-testfile-3.mid

run4: ; ./midi-text-dump2 midi-testfile-4.mid
    
